spring:
  application:
    name: spring-ai-admin
  profiles:
    active: local
  config:
    import: classpath:codegen.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
